spring:
  application:
    name: GanmaApplication
  sql:
    init:
      mode: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ganma_shop_db?&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  thymeleaf:
    prefix: classpath:/templates/   # 模板文件的位置
    suffix: .html                   # 模板文件的后缀
    mode: HTML                      # 模板解析模式
    cache: false

server:
  port: 8081
#  address: 255.255.0.0

mybatis:
  mapper-locations: classpath:mybatis/*.xml      # mybatis mapper映射文件位置

file:
  image-dir: src/main/resources/static/